[package]
name = "track"
version = "0.1.0"
authors = ["alexander.linne <alexander.linne@stud.uni-goettingen.de>"]
edition = "2018"

[dependencies]
clap = {version = "~2.32.0", features = ["yaml"]}
serde_json = "1.0"
structopt = "0.2"
