[package]
name = "analyze"
version = "0.1.0"
authors = ["alexander.linne <alexander.linne@stud.uni-goettingen.de>"]
edition = "2018"

[dependencies]
error-chain = "0.12.0"
libc = "0.2"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"

