[package]
name = "preload"
version = "0.1.0"
authors = ["alexander.linne <alexander.linne@stud.uni-goettingen.de>"]
edition = "2018"

[lib]
crate-type = ["dylib"]

[dependencies]
analyze_base = { path = "../analyze_base" }
libc = "0.2"
serde_json = "1.0"
